server:
  port: 8888

spring:
    datasource:
        name: filestorage
        url: jdbc:mysql://60.205.228.42:3306/demo_mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: Ld203203
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
      database: 0
      host: 60.205.228.42
      port: 6379
      password: X5553525
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 0
    jmx:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.refutrue.athena


